[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "max"
authors = [{name = "Arjun", email = "arjun_sehajpal_ZSinc"}]
dynamic = ["version", "description"]